// Generated by CoffeeScript 1.4.0
(function() {
  var URL, channelsToWorkers, client, currentNick, currentPmUser, data, emitToAllWorkers, irc, passEvent, pmUsers, sha1, storage, tabToPreviousPage, tabs, widgets, _ref, _ref1, _ref2,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __hasProp = {}.hasOwnProperty;

  widgets = require("sdk/widget");

  URL = require('sdk/url').URL;

  tabs = require('sdk/tabs');

  data = require("sdk/self").data;

  storage = require("sdk/simple-storage").storage;

  sha1 = require('./sha1.js').sha1;

  irc = require('./bundle');

  if ((_ref = storage.messagesHistory) == null) {
    storage.messagesHistory = {};
  }

  if ((_ref1 = storage.privateMessagesHistory) == null) {
    storage.privateMessagesHistory = {};
  }

  pmUsers = ['Resonance-bot'];

  currentPmUser = 'Resonance-bot';

  currentNick = (_ref2 = storage.nick) != null ? _ref2 : 'Resonance-dev';

  client = new irc.Client('chat.freenode.net', currentNick, {
    debug: false
  });

  client.addListener('message', function(from, to, message) {
    var _base, _ref3;
    if (to !== currentNick) {
      channelsToWorkers[to].port.emit('message', from, to, message);
      if ((_ref3 = (_base = storage.messagesHistory)[to]) == null) {
        _base[to] = [];
      }
      return storage.messagesHistory[to].push({
        'author': from,
        'message': message
      });
    }
  });

  client.addListener('pm', function(from, message) {
    var _base, _ref3;
    if (from === 'Resonance-bot' && message.match(/^announce /)) {
      message = message.replace('announce ', '');
      return emitToAllWorkers('announce', message);
    } else if (from === 'Resonance-bot' && message.match(/^topPages /)) {
      message = message.replace('topPages ', '');
      return emitToAllWorkers('topPages', message);
    } else {
      if (!(__indexOf.call(pmUsers, from) >= 0)) {
        pmUsers.push(from);
        emitToAllWorkers('pmUsers', pmUsers);
      }
      if ((_ref3 = (_base = storage.privateMessagesHistory)[from]) == null) {
        _base[from] = [];
      }
      storage.privateMessagesHistory[from].push({
        'author': from,
        'message': message
      });
      if (from === currentPmUser) {
        return emitToAllWorkers('privateMessage', from, currentNick, message);
      }
    }
  });

  client.addListener('part', function(chan, nick) {
    if (nick !== currentNick) {
      return channelsToWorkers[chan].port.emit('part', chan, nick);
    }
  });

  passEvent = function(eventName) {
    return client.addListener(eventName, function(chan, a, b, c, d, e, f, g, h, i) {
      if (channelsToWorkers[chan] != null) {
        return channelsToWorkers[chan].port.emit(eventName, chan, a, b, c, d, e, f, g, h, i);
      }
    });
  };

  passEvent('names');

  passEvent('join');

  emitToAllWorkers = function(eventName, a, b, c, d, e, f, g, h, i) {
    var chan, worker, _results;
    _results = [];
    for (chan in channelsToWorkers) {
      if (!__hasProp.call(channelsToWorkers, chan)) continue;
      worker = channelsToWorkers[chan];
      _results.push(worker.port.emit(eventName, a, b, c, d, e, f, g, h, i));
    }
    return _results;
  };

  tabToPreviousPage = [];

  channelsToWorkers = {};

  tabs.on('ready', function(tab) {
    var chan, currentTab, i, worker, _base, _ref3, _ref4, _ref5;
    currentTab = -1;
    i = 0;
    while (i < tabs.length) {
      if (tab === tabs[i]) {
        currentTab = i;
      }
      i++;
    }
    if (tabToPreviousPage[currentTab] != null) {
      client.part(tabToPreviousPage[currentTab].chan);
      delete channelsToWorkers[tabToPreviousPage[currentTab].chan];
    }
    chan = '#' + sha1(tab.url.host + tab.title).toString();
    if (chan === '#84642551eb26c07c7895b86e3fb0b7d70fd6ff97') {
      console.log('########################################################\n error ?');
    }
    console.log(tab.url);
    console.log(tab.title);
    client.join(chan);
    client.say('Resonance-bot', 'enter ' + tab.url + ' ' + chan);
    tabToPreviousPage[currentTab] = {
      'url': tab.url,
      'chan': chan
    };
    worker = tab.attach({
      contentScriptFile: [data.url("lib/jquery.js"), data.url("lib/angular.min.js"), data.url("content-built.js"), data.url("controllers/app.js"), data.url("controllers/ResonanceController.js"), data.url("controllers/IrcController.js"), data.url("controllers/MessagesController.js"), data.url("controllers/UsersController.js"), data.url("controllers/TopPagesController.js"), data.url("controllers/SettingsController.js"), data.url("controllers/PrivateMessagesController.js"), data.url("controllers/PrivateUsersController.js")]
    });
    channelsToWorkers[chan] = worker;
    worker.port.emit('appSize', (_ref3 = storage.appSize) != null ? _ref3 : '100');
    worker.port.emit('chan', chan);
    worker.port.emit('nick', currentNick);
    worker.port.emit('messagesHistory', (_ref4 = storage.messagesHistory[chan]) != null ? _ref4 : []);
    worker.port.emit('pmUsers', pmUsers);
    if ((_ref5 = (_base = storage.privateMessagesHistory)[currentPmUser]) == null) {
      _base[currentPmUser] = [];
    }
    worker.port.emit('pmUser', currentPmUser, storage.privateMessagesHistory[currentPmUser]);
    worker.port.on('say', function(to, message) {
      client.say(to, message);
      return worker.port.emit('message', currentNick, to, message);
    });
    worker.port.on('privateMessage', function(user, message) {
      var _base1, _ref6;
      client.say(user, message);
      if ((_ref6 = (_base1 = storage.privateMessagesHistory)[user]) == null) {
        _base1[user] = [];
      }
      storage.privateMessagesHistory[user].push({
        'author': currentNick,
        'message': message
      });
      return emitToAllWorkers('privateMessage', currentNick, user, message);
    });
    worker.port.on('getTopPages', function() {
      return client.say('Resonance-bot', 'ask');
    });
    worker.port.on('startPmUser', function(user) {
      var _base1, _ref6;
      currentPmUser = user;
      if (!(__indexOf.call(pmUsers, user) >= 0)) {
        pmUsers.push(user);
        emitToAllWorkers('pmUsers', pmUsers);
      }
      if ((_ref6 = (_base1 = storage.privateMessagesHistory)[user]) == null) {
        _base1[user] = [];
      }
      return emitToAllWorkers('pmUser', currentPmUser, storage.privateMessagesHistory[user]);
    });
    worker.port.on("newNick", function(nick) {
      storage.nick = nick;
      currentNick = nick;
      return worker.port.emit('message', 'Resonance', currentNick, 'Your new nick will be saved and available as soon as you restart firefox.');
    });
    return worker.port.on("newAppSize", function(height) {
      return storage.appSize = height;
    });
  });

  tabs.on('close', function(tab) {
    var chan;
    chan = '#' + sha1(tab.url.host + tab.title).toString();
    client.part(chan);
    delete tabToPreviousPage[tab];
    return delete channelsToWorkers[chan];
  });

}).call(this);
