// Generated by CoffeeScript 1.6.2
(function() {
  var URL, data, irc, panel, sha1, storage, tabs;

  data = require("sdk/self").data;

  panel = require("sdk/panel").Panel({
    'width': 800,
    'height': 200,
    'contentURL': data.url("panel.html"),
    'contentScriptFile': [data.url("lib/angular.min.js"), data.url("lib/jquery.js"), data.url("panel_controllers/panel.js")]
  });

  require("sdk/widget").Widget({
    'id': "widget-open-settings",
    'label': "Resonance",
    'contentURL': data.url("History.png"),
    'panel': panel
  });

  panel.port.on('test', function(msg) {
    return console.log(msg);
  });

  URL = require('sdk/url').URL;

  tabs = require('sdk/tabs');

  data = require("sdk/self").data;

  storage = require("sdk/simple-storage").storage;

  sha1 = require('./sha1.js').sha1;

  irc = require('./_irc.js');

  tabs.on('ready', function(tab) {
    console.log('Tab ready');
    if (resonanceIsActivated) {
      return console.log('app started');
    }
  });

}).call(this);
